# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json

stages:
  - build
  - deploy
  - sync
  - invalidate

build:
  stage: build
  image: registry.gitlab.com/pages/hugo
  script: hugo --cleanDestinationDir
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  artifacts:
    paths:
      - public/
    expire_in: 1 week

deploy:
  stage: deploy
  image:
    name: amaysim/stacker
    entrypoint: ["/bin/sh", "-c"]
  environment:
    name: production
  script: stacker build stacker.yml --tail --recreate-failed
  only:
    - master

sync:
  stage: sync
  image:
    name: amazon/aws-cli
    entrypoint: ["/bin/sh", "-c"]
  environment:
    name: production
  script: aws s3 sync --no-progress --delete --cache-control 'max-age=3155695200' public/ "s3://${DOMAIN_NAME}/"
  only:
    - master

invalidate:
  stage: invalidate
  image:
    name: amazon/aws-cli
    entrypoint: ["/bin/sh", "-c"]
  environment:
    name: production
  script: aws cloudfront create-invalidation --distribution-id="$(aws cloudformation --region us-east-1 describe-stacks --stack-name "${AWS_CLOUDFORMATION_STACK_NAME}" --query 'Stacks[0].Outputs[?OutputKey==`CloudFrontDistributionId`].OutputValue' --output=text)" --paths "/*"
  only:
    - master
