# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json

stages:
  - build
  - deploy
  - sync
  - invalidate

build:
  stage: build
  image: registry.gitlab.com/pages/hugo:latest
  script:
    - make build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  artifacts:
    paths:
      - public/
    expire_in: 1 week

deploy:
  stage: deploy
  image: amaysim/stacker:latest
  environment:
    name: production
  script:
    - make deploy
  only:
    - master

sync:
  stage: sync
  image: amazon/aws-cli
  environment:
    name: production
  script:
    - make syncToS3
  only:
    - master

invalidate:
  stage: invalidate
  image: amazon/aws-cli
  environment:
    name: production
  script:
    - make cacheInvalidation
  only:
    - master
