baseURL = "https://aarongorka.com/"
languageCode = "en-us"
title = "Aaron's Blog"
author = "Aaron Gorka"
theme = "hugo-theme-minos"
pygmentsCodeFences = true
pygmentsuseclasses  = true
pluralizelisttitles = false
uglyurls = true
enableRobotsTXT = true

[permalinks]
blog  = "blog/:slug/"

[params]
    smartToc = true

  [[params.social]]
    icon = "github"
    url = "https://github.com/aarongorka"
    weight = 2

  [[params.social]]
    icon = "linkedin"
    url = "https://www.linkedin.com/in/aarongorka/"
    weight = 1

  [[params.social]]
    icon = "gitlab"
    url = "https://gitlab.com/aarongorka/"
    weight = 3

  [[params.social]]
    icon = "medium"
    url = "https://medium.com/@aarongorka"

  [[params.social]]
    icon = "docker"
    url = "https://hub.docker.com/u/aarongorka/"
    weight = 99
