baseURL = "https://aarongorka.com/"
languageCode = "en-us"
title = "Aaron's Blog"
author = "Aaron Gorka"
theme = "hugo-theme-minos"
pygmentsCodeFences = true
pluralizelisttitles = false
enableRobotsTXT = true
enableEmoji = true

[permalinks]
blog  = "blog/:slug/"

[menu]
    [[menu.main]]
        identifier = "slides"
        name = "slides"
        url = "https://slides.aarongorka.com"
        weight = 1
    [[menu.main]]
        identifier = "cv"
        name = "cv"
        url = "https://cv.aarongorka.com"
        weight = 2

[params]
    smartToc = true

  [[params.social]]
    icon = "linkedin"
    url = "https://www.linkedin.com/in/aarongorka/"
    weight = 1

  [[params.social]]
    icon = "github"
    url = "https://github.com/aarongorka"
    weight = 2

  [[params.social]]
    icon = "gitlab"
    url = "https://gitlab.com/aarongorka/"
    weight = 3

  [[params.social]]
    icon = "medium"
    url = "https://medium.com/@aarongorka"
    weight = 4

  [[params.social]]
    icon = "slideshare"
    url = "https://slides.aarongorka.com"
    weight = 5

  [[params.social]]
    icon = "docker"
    url = "https://hub.docker.com/r/aarongorka/"
    weight = 6
