version: '3'
services:
  hugo:
    image: registry.gitlab.com/pages/hugo:latest
    env_file: .env
    entrypoint: ["hugo"]
    volumes:
      - .:/srv/app:Z
    working_dir: /srv/app
    ports:
      - "1313:1313"
    command: "server --buildDrafts --bind 0.0.0.0"
  aws:
    image: amaysim/aws:1.2.0
    env_file: .env
    volumes:
      - .:/srv/app:Z
    working_dir: /srv/app
  stacker:
    image: amaysim/stacker:latest
    env_file: .env
    entrypoint: stacker
    volumes:
      - .:/stacks:Z
      - ~/.aws:/root/.aws:Z
  cfn-python-lint:
    image: amaysim/cfn-python-lint:latest
    network_mode: "none"
    entrypoint: ''
    env_file: .env
    working_dir: /srv/app
    volumes:
      - .:/srv/app:Z
  node:
    image: node:latest
    working_dir: /opt/app
    volumes:
      - .:/opt/app:Z
      - ~/.yarn-cache:/usr/local/share/.cache/yarn/v1:Z
  write-good:
    image: aarongorka/write-good:latest
    network_mode: "none"
    working_dir: /srv/app
    volumes:
      - .:/srv/app:Z
